### ISSUE TITLE
Changer l'url du  serveur

### ISSUE THREAD

**Issue by diouck** [etalab/addok#139]
Bonjour 
Je voudrai savoir comment on pourrait  changer  l'url  http://127.0.0.1:8000  par  http://212.47.238.202:8000 ? 
Merci

**Comment by yohanboniface** [comment]
Avec le serveur de debug:
```
addok serve --port 8000 --host 212.47.238.202
addok --help  # pour en savoir plus
```
Avec Gunicorn:
```
gunicorn addok.server:app -b 212.47.238.202:8000
gunicorn --help  # pour en savoir plus
```

**Comment by diouck** [comment]
Merci mais j'ai toujours la même erreur 

<code>
(addok)abdou.diouck@ubuntu-srv1:~/ban$ gunicorn addok.server:app -b 192.168.0.104:8000
[2016-01-06 12:16:04 +0100] [8973] [INFO] Starting gunicorn 19.3.0
[2016-01-06 12:16:04 +0100] [8973] [ERROR] Connection in use: ('192.168.0.104', 8000)
[2016-01-06 12:16:04 +0100] [8973] [ERROR] Retrying in 1 second.
[2016-01-06 12:16:05 +0100] [8973] [ERROR] Connection in use: ('192.168.0.104', 8000)
[2016-01-06 12:16:05 +0100] [8973] [ERROR] Retrying in 1 second.
[2016-01-06 12:16:06 +0100] [8973] [ERROR] Connection in use: ('192.168.0.104', 8000)
[2016-01-06 12:16:06 +0100] [8973] [ERROR] Retrying in 1 second.
[2016-01-06 12:16:07 +0100] [8973] [ERROR] Connection in use: ('192.168.0.104', 8000)
[2016-01-06 12:16:07 +0100] [8973] [ERROR] Retrying in 1 second.
[2016-01-06 12:16:08 +0100] [8973] [ERROR] Connection in use: ('192.168.0.104', 8000)
[2016-01-06 12:16:08 +0100] [8973] [ERROR] Retrying in 1 second.
[2016-01-06 12:16:09 +0100] [8973] [ERROR] Can't connect to ('192.168.0.104', 8000)
(addok)abdou.diouck@ubuntu-srv1:~/ban$ addok serve --port 8000 --host 192.168.0.104
Traceback (most recent call last):
  File "/home/abdou.diouck/ban/addok/bin/addok", line 9, in <module>
    load_entry_point('addok==0.4.0', 'console_scripts', 'addok')()
  File "/home/abdou.diouck/ban/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 43, in main
    from addok import config
  File "/home/abdou.diouck/ban/addok/lib/python3.4/site-packages/addok/config/__init__.py", line 5, in <module>
    from .default import *  # noqa
  File "/home/abdou.diouck/ban/addok/lib/python3.4/site-packages/addok/config/default.py", line 2
    om pathlib import Path
gunicorn addok.server:app -b 192.168.0.104:8000
</code>

**Comment by diouck** [comment]
En faite j'essaye de l'installer depuis un serveur distant donc je ne peux pas accéder à  http://127.0.0.1:8000

**Comment by yohanboniface** [comment]
> [ERROR] Connection in use: ('192.168.0.104', 8000)

Un indice ;)

**Comment by yohanboniface** [comment]
(Le port 8000 est sûrement occupé par un autre process.)

**Comment by diouck** [comment]
Oui en effet le port 8000  était deja pris je viens de le remplacer par 8888 mais j'ai toujours la meme erreur. Je vais creuser davantage.

**Comment by diouck** [comment]
C'est bon j'ai trouver la solution
Il fallait l'installer directement dans le serveur web
/var/www/html/ban
Merci pour tout et ca marche nickel
