### ISSUE TITLE
Erreur 500 KeyError : 'name'

### ISSUE THREAD

**Issue by ksahin** [etalab/addok#18]
J'ai un soucis avec une requête en particulier : 

```
 - - [03/Feb/2015 13:47:57] "GET /search/?q=1%20route%20express%2071300%20montceau%20les%20mines HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kevin/addok/addok/server.py", line 41, in app
    response = on_search(request)
  File "/home/kevin/addok/addok/server.py", line 73, in on_search
    return serve_results(results, query=query)
  File "/home/kevin/addok/addok/server.py", line 94, in serve_results
    "features": [r.to_geojson() for r in results]
  File "/home/kevin/addok/addok/server.py", line 94, in <listcomp>
    "features": [r.to_geojson() for r in results]
  File "/home/kevin/addok/addok/core.py", line 120, in to_geojson
    properties['name'])
KeyError: 'name'

```
Sinon pas de soucis avec cette nouvelle api, bien plus réactif que bano-geocode, et les résultats m'ont l'air plus pertinent a priori.

**Comment by yohanboniface** [comment]
Merci pour les retours, et le rapport de bug, ça devrait être corrigé :)
