### ISSUE TITLE
GEOHASHMEMBERS u09vej04 [NEIGHBORS 0]

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#76]
Runing in shell, quoted from doc:
```
GEOHASHMEMBERS u09vej04 [NEIGHBORS 0]
```

Give an error:
```
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/bin/addok", line 9, in <module>
    load_entry_point('addok==0.2.0', 'console_scripts', 'addok')()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 50, in main
    cli()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 450, in __call__
    self.handle_command(command)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 440, in handle_command
    return getattr(self, fx_name)(arg)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 380, in do_geohashmembers
    key = compute_geohash_key(geoh, with_neighbors != '0')
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 40, in compute_geohash_key
    neighbors = [geohash_key(n) for n in neighbors]
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 40, in <listcomp>
    neighbors = [geohash_key(n) for n in neighbors]
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/index_utils.py", line 48, in geohash_key
    return 'g|{}'.format(s)
ValueError: geohash code is [0123456789bcdefghjkmnpqrstuvwxyz]+
```

**Comment by yohanboniface** [comment]
And without the `[]`?

**Comment by frodrigo** [comment]
No error without the []. But the [] is in the doc ;).
