### ISSUE TITLE
INTERSECT rue des lilas [LIMIT 100]

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#77]
Runing in shell, quoted from doc:
```
INTERSECT rue des lilas [LIMIT 100]
```

Give an error:
```
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/bin/addok", line 9, in <module>
    load_entry_point('addok==0.2.0', 'console_scripts', 'addok')()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 50, in main
    cli()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 450, in __call__
    self.handle_command(command)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 440, in handle_command
    return getattr(self, fx_name)(arg)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 412, in do_intersect
    limit = int(limit)
ValueError: invalid literal for int() with base 10: ' 100]'
```

**Comment by yohanboniface** [comment]
Same here, `[]` means optional option, but you should not write them actually ;)

**Comment by frodrigo** [comment]
Ok without []
