### ISSUE TITLE
SEARCH rue des Lilas [CENTER 0.0 0.0]

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#78]
Runing in shell:
```
SEARCH rue des Lilas [CENTER 0.0 0.0]
```

Give an error:
```
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/bin/addok", line 9, in <module>
    load_entry_point('addok==0.2.0', 'console_scripts', 'addok')()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/bin/__init__.py", line 50, in main
    cli()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 450, in __call__
    self.handle_command(command)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 440, in handle_command
    return getattr(self, fx_name)(arg)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 180, in do_search
    self._search(query)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/debug.py", line 149, in _search
    lon = float(lon)
ValueError: could not convert string to float: '0.0]'
```

**Comment by frodrigo** [comment]
Work without "[" and "]"
