### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by frodrigo** [etalab/addok#84]
This particular query raise an error on my personal server and the same on public one at http://api-adresse.data.gouv.fr/
```
/search?type=street&q=hjkl
```

```
[01/Jul/2015 18:53:59] "GET /search?type=street&q=hjkl HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 65, in app
    response = View.serve(endpoint, request)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 105, in serve
    response = view.get()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 160, in get
    lat=lat, lon=lon, **filters)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 715, in search
    return helper(query, lat=lat, lon=lon, **filters)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 348, in __call__
    if step():
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 408, in step_bucket_with_meaningful
    self.new_bucket(self.keys, self.SMALL_BUCKET_LIMIT)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 599, in new_bucket
    self.bucket = self.intersect(keys, limit)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 582, in intersect
    ids = DB.zrevrange(keys[0], 0, limit - 1)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1733, in zrevrange
    return self.execute_command(*pieces, **options)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by dzaouch** [comment]
Hi,

I got the same error by using the csv, so i don't know which line makes it crashes and why.

Can you tell me why it's crashing ?

[2016-06-24 12:49:42 +0200] [14784] [ERROR] Error handling request /csv
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
