### ISSUE TITLE
/search/csv does not accept single column CSV

### ISSUE THREAD

**Issue by cquest** [etalab/addok#90]
For example:

adresse
108 rue du Bac 75007 Paris
108 rue Gambetta 44000 Nantes
108 rue Jean-Pierre-Timbaud 75011 Paris
108 rue Nationale 59254 Ghyvelde
109 avenue de Gairaut 06100 Nice
109 avenue Pierre-de-Coubertin 53010 Laval Cedex

**Comment by frodrigo** [comment]
Still not working for me

**Comment by frodrigo** [comment]
Still not working. Now there is an error on server:
```
[16/Jul/2015 12:27:01] "POST /search/csv HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 66, in app
    response = View.serve(endpoint, request, **kwargs)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 104, in serve
    response = view.post(**kwargs)
  File "/home/fred/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 273, in post
    writer.writerow(row)
  File "/usr/lib/python3.4/csv.py", line 153, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python3.4/csv.py", line 149, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: None
```

**Comment by yohanboniface** [comment]
Can you give me the file your are using?

**Comment by frodrigo** [comment]
This file produce the ValueError: dict contains fields not in fieldnames: None
```
q
"50 Bv de la Plage, Arcachon",""
```

This one: _csv.Error: Could not determine delimiter
```
q
"50 Bv de la Plage, Arcachon"
```
